version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8.6
        environment:
          DJANGO_SETTINGS_MODULE: base.settings.circleci
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            cp .env.example .env
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: |
            coverage run --omit '.venv/*' --source='.' manage.py test -v 2
            coverage html
      - store_test_results: # TODO: need to fix
          path: htmlcov
      - store_artifacts:
          path: htmlcov
          destination: htmlcov