name: Deploy To Server

on:
  push:
    branches: 
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo {{ secrets.SSH_PRIVATE_KEY }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd base.django/
            git pull
