name: Deploy To Server

on:
  push:
    branches: 
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo {{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: executing remote ssh commands using ssh key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd base.django/
            git pull
